Adding metrics for GANs evaluation
szmazurek/GaNDLF pull request #27
Opened 2024-03-10 08:43 UTC by szmazurek

Fixes #812

## Proposed Changes
- currently implemented: FID, SSIM, LIPIS
- LPIPS compatibile with 2D and 3D, FID only for 2D

## Checklist

- [X] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [X] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [X] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [X] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [X] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [X] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [X] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

2024-03-12 13:18 UTC, sarthakpati commented
There is duplication from here: https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/metrics/synthesis.py. This is the base we are using for the `generate_metrics` module [[ref](https://mlcommons.github.io/GaNDLF/usage/#generate-metrics)].

I would recommend extending this module with additional metrics, and calling from here as needed. Additionally, once you add a metric, the corresponding unit test should be a simple extension of this [[ref](https://github.com/mlcommons/GaNDLF/blob/master/testing/test_full.py#L3051)].

2024-03-12 21:12 UTC, szmazurek commented
> There is duplication from here: https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/metrics/synthesis.py. This is the base we are using for the `generate_metrics` module [[ref](https://mlcommons.github.io/GaNDLF/usage/#generate-metrics)].
> 
> I would recommend extending this module with additional metrics, and calling from here as needed. Additionally, once you add a metric, the corresponding unit test should be a simple extension of this [[ref](https://github.com/mlcommons/GaNDLF/blob/master/testing/test_full.py#L3051)].

Sure, will move it tomorrow

2024-03-15 13:46 UTC, sarthakpati requested changes
Requesting a few changes:

- Change `raise` to `assert` - code coverage and consistency.
- I may I have requested the 2D image check at multiple places. They should be present in both places, i.e., where the module is being defined (say `GANDLF/metrics/gan_utils/fid`) and as well as where they are being invoked (say `GANDLF/metrics/synthesis`). This will ensure that the `assert` gets triggered regardless of where the user is invoking the code from.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +            )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +                )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +                )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +            raise TypeError("Got unknown input to argument `feature`")
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +            )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +            raise ValueError("Argument `normalize` expected to be a bool")
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +            )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +        )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +        raise ValueError(f"Unknown converter type {converter_type}")
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/lpip.py
> +            )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/lpip.py
> +            )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/lpip.py
> +            )
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/synthesis.py
> +        raise ValueError("FID is not supported for batch size 1")
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/synthesis.py
> +        raise ValueError("FID is not supported for batch size 1")
Change to `assert`.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    if not (_valid_img(img1, normalize) and _valid_img(img2, normalize)):
Put an assert for 2D image check before this line to make it explicit that this module only works for 2D images.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    return (img.ndim == 4 or img.ndim == 5) and value_check
This seems to be same/similar to the check in FID. Can they be combined?

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    if not (_valid_img(img1, normalize) and _valid_img(img2, normalize)):
Put an assert for 2D image check before this line to make it explicit that this module only works for 2D images.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/lpip.py
> +    determine_converter,
This function is a duplicate of what is there in `GANDLF.models.ModelBase`. Let's keep a note of it so that we combine them when we are merging upstream.

2024-03-15 13:46 UTC, sarthakpati commented on GANDLF/metrics/synthesis.py
> +    def _get_features_size(params: Dict[str, Any]) -> int:
Put an assert for 2D image check before this line to make it explicit that this module only works for 2D images.

2024-03-15 17:31 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +            )
done

2024-03-15 17:31 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +                )
done

2024-03-15 17:31 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +            )
done

2024-03-15 17:31 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +                )
done

2024-03-15 17:32 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +            raise TypeError("Got unknown input to argument `feature`")
done

2024-03-15 17:32 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +            raise ValueError("Argument `normalize` expected to be a bool")
done

2024-03-15 17:33 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +            )
done

2024-03-15 17:37 UTC, szmazurek commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +        )
done

2024-03-15 17:38 UTC, szmazurek commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +        raise ValueError(f"Unknown converter type {converter_type}")
done

2024-03-15 17:42 UTC, szmazurek commented on GANDLF/metrics/gan_utils/lpip.py
> +            )
done

2024-03-15 17:57 UTC, szmazurek commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    if not (_valid_img(img1, normalize) and _valid_img(img2, normalize)):
Hmm, but that would not be true - we have lpips working also for 3D images.

2024-03-15 17:58 UTC, szmazurek commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    if not (_valid_img(img1, normalize) and _valid_img(img2, normalize)):
Same as above

2024-03-15 18:15 UTC, szmazurek commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    return (img.ndim == 4 or img.ndim == 5) and value_check
Hmm, if fact maybe, but some considerations - we would have to add a flag that indicates whether we are using it for fid or lpip metrics and add conditionals (as the checks for fid and lpips are different) - wouldn't this make the function more complex and hard to debug? I may write similar for fid (currently fid does similar thing but using separate checks in different places.)

2024-03-15 18:21 UTC, szmazurek commented on GANDLF/metrics/synthesis.py
> +    def _get_features_size(params: Dict[str, Any]) -> int:
added

2024-03-15 18:24 UTC, szmazurek commented on GANDLF/metrics/gan_utils/lpip.py
> +    determine_converter,
noted

2024-03-17 17:42 UTC, sarthakpati requested changes
Please ensure that the comment style is consistent for all functions/classes, and I am guessing `Raises` is no longer needed in the comments after everything has been converted to `assert`...

2024-03-17 17:42 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +            If ``reset_real_features`` is not an ``bool``
I am guessing this is redundant, now?

2024-03-17 17:42 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +                If `matplotlib` is not installed
I am guessing this is redundant, now?

2024-03-17 17:42 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/lpip.py
> +                If `matplotlib` is not installed
I am guessing this is redundant, now?

2024-03-17 17:42 UTC, sarthakpati commented on GANDLF/metrics/synthesis.py
> +    """
Update comment style

2024-03-17 17:42 UTC, sarthakpati commented on GANDLF/metrics/synthesis.py
> +    """
Update comment style

2024-03-17 17:42 UTC, sarthakpati commented on GANDLF/metrics/synthesis.py
> +    """
Update comment style.

2024-03-18 09:22 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +            If ``reset_real_features`` is not an ``bool``
Wanted to keep it to tell which errors we are going to catch explicitly, nevertheless I believe you are right - can be removed.

2024-03-18 09:25 UTC, szmazurek commented on GANDLF/metrics/gan_utils/fid.py
> +                If `matplotlib` is not installed
Actually, entire method is. Removing

2024-03-18 09:25 UTC, szmazurek commented on GANDLF/metrics/gan_utils/lpip.py
> +                If `matplotlib` is not installed
As above, entire method redundant and removed

2024-03-18 09:29 UTC, szmazurek commented on GANDLF/metrics/synthesis.py
> +    """
Updated mentioned and other comment styles - indeed the spacing was wrong there

2024-03-18 13:11 UTC, sarthakpati requested changes
The comment style needs to be updated (see some of my example suggestions for reference) for consistency.

2024-03-18 13:11 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +    and X_y ~ N(mu_2, sigm_2) is d^2 = ||mu_1 - mu_2||^2 + Tr(sigm_1 + sigm_2 - 2*sqrt(sigm_1*sigm_2)).
```suggestion
    """
    This function calculates the adjusted version of `Fid Score`_. The Frechet Inception Distance between two multivariate Gaussians X_x ~ N(mu_1, sigm_1)
    and X_y ~ N(mu_2, sigm_2) is d^2 = ||mu_1 - mu_2||^2 + Tr(sigm_1 + sigm_2 - 2*sqrt(sigm_1*sigm_2)).
```

2024-03-18 13:11 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/fid.py
> +        FID = \|\mu - \mu_w\|^2 + tr(\Sigma + \Sigma_w - 2(\Sigma \Sigma_w)^{\frac{1}{2}})
```suggestion
    """
    This function calculates the Fréchet inception distance (FID_) which is used to access the quality of generated images.
    .. math::
        FID = \|\mu - \mu_w\|^2 + tr(\Sigma + \Sigma_w - 2(\Sigma \Sigma_w)^{\frac{1}{2}})
```

2024-03-19 12:55 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    return (img.ndim == 4 or img.ndim == 5) and value_check
I think all these checks can be put in a `utils` submodule under this one. Also, would `metrics` be a better name for this module rather than `functional`?

2024-03-19 14:41 UTC, szmazurek commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    return (img.ndim == 4 or img.ndim == 5) and value_check
Not really sure what do you mean with "under this one"? You mean GANDLF/utils? With the naming - yeah, we can go this way, but isn't that going to be confusing when in metrics folder we have gan_utils and in this one we would have another metrics folder? Also agree that functional is not really descriptive, I followed torchmetrics style of code organisation.

2024-03-21 16:45 UTC, sarthakpati commented on GANDLF/metrics/gan_utils/functional/lpips.py
> +    return (img.ndim == 4 or img.ndim == 5) and value_check
Ah okay. This is no longer needed.

2024-03-22 09:52 UTC, szmazurek commented
Hey, I belive the full style cleaning was done with the yesterday commit. If you do not find any other issues I believe we can merge.

2024-03-22 13:42 UTC, sarthakpati approved these changes
LGTM

2024-03-22 13:54 UTC, merged