Implementing GAN compute utils
szmazurek/GaNDLF pull request #28
Opened 2024-03-10 08:56 UTC by szmazurek

Fixes #813

## Proposed Changes
- added all compute utilities required to train the network
- they are kept separate, as the GAN folder will serve as closed testing playground for the synthesis solutions

## Checklist
- [X] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [X] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [X] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [X] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [X] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [ ] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [ ] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

2024-03-12 13:28 UTC, sarthakpati requested changes
Requesting some minor changes. Additionally, these:

- Rename `GAN` to `synthesis`, because we might want to add in diffusion models at some point of time as well.
- Update the function documentation style according to how the rest of it is structured. See [this](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/compute/forward_pass.py#L35-L48) for reference.

2024-03-12 13:28 UTC, sarthakpati commented on GANDLF/GAN/compute/forward_pass.py
> +        # aggregator = torchio.inference.GridAggregator(
Put a comment (and related documentation) that the synthesis framework only supports full image validation.

2024-03-12 13:28 UTC, sarthakpati commented on GANDLF/GAN/compute/forward_pass.py
> +            )
Replace with `assert` - improves code coverage, and it is consistent with what is happening in the rest of the code.

2024-03-12 13:28 UTC, sarthakpati commented on GANDLF/GAN/compute/forward_pass.py
> +            )
Replace with `assert` - improves code coverage, and it is consistent with what is happening in the rest of the code.

2024-03-12 13:28 UTC, sarthakpati commented on GANDLF/GAN/compute/inference_loop.py
> +        raise NotImplementedError("OpenVINO inference is not yet implemented")
Replace with `assert` - improves code coverage, and it is consistent with what is happening in the rest of the code.

2024-03-12 13:28 UTC, sarthakpati commented on GANDLF/GAN/compute/inference_loop.py
> +        raise NotImplementedError("OpenVINO inference is not yet implemented")
Replace with `assert` - improves code coverage, and it is consistent with what is happening in the rest of the code.

2024-03-12 13:28 UTC, sarthakpati commented on GANDLF/GAN/compute/generic.py
> +    can be 2 for 2D or 3 for 3D.
```suggestion
        dimension (int): The dimension of the images in a given problem. Can be `2` for 2D or `3` for 3D.
```

2024-03-12 20:19 UTC, szmazurek commented on GANDLF/GAN/compute/forward_pass.py
> +        # aggregator = torchio.inference.GridAggregator(
Done

2024-03-12 20:52 UTC, szmazurek commented on GANDLF/GAN/compute/forward_pass.py
> +            )
Done

2024-03-12 20:52 UTC, szmazurek commented on GANDLF/GAN/compute/forward_pass.py
> +            )
Done

2024-03-12 20:58 UTC, szmazurek commented on GANDLF/GAN/compute/inference_loop.py
> +        raise NotImplementedError("OpenVINO inference is not yet implemented")
Done

2024-03-12 20:59 UTC, szmazurek commented on GANDLF/GAN/compute/inference_loop.py
> +        raise NotImplementedError("OpenVINO inference is not yet implemented")
Done, plus no idea why I repeated that condition lol

2024-03-12 21:02 UTC, szmazurek commented
> Requesting some minor changes. Additionally, these:
> 
> * Rename `GAN` to `synthesis`, because we might want to add in diffusion models at some point of time as well.
> * Update the function documentation style according to how the rest of it is structured. See [this](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/compute/forward_pass.py#L35-L48) for reference.

Regarding first one - noted that, will do separate pr for that when the rest will be merged
Regarding second one - 5 mins and push

2024-03-13 16:39 UTC, sarthakpati reviewed
Minor stylistic changes and one philosophical comment.

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/forward_pass.py
> +    # I really do not get it
Huh? 😆

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/generic.py
> +    """Creates a latent vector of given size and adjusts the dimensions
Update comment style (for reference, see the documentation for `create_pytorch_objects_gan`).

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/generic.py
> +    Function to get the fixed latent vector for inference or validation.
Update comment style (for reference, see the documentation for `create_pytorch_objects_gan`).

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/generic.py
> +    parameters, train_csv=None, val_csv=None, device="cpu"
Add typing information.

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/inference_loop.py
> +    """Normalizes the input tensor to be in the range [0, 1]. Operation is
Update comment style (for reference, see the documentation for `inference_loop_gan`).

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/inference_loop.py
> +        """Utility function to normalize the input image, the same as in
Update comment style (for reference, see the documentation for `inference_loop_gan`).

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/inference_loop.py
> +    )  # remaining samples for last iteration
Run `black` on this again.
```suggestion
    # how many iterations to run
    n_iterations = (
        n_generated_samples // batch_size
    )  
    # remaining samples for last iteration
    remaining_samples = (
        n_generated_samples % batch_size
    )  
```

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/loss_and_metric.py
> +    This function computes the output of a metric function.
Update comment style.

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/loss_and_metric.py
> +        loss (Tensor): The computed loss from the label and the prediction.
```suggestion
    Compute the loss value for adversarial generative networks.

    Args:
        predictions (Tensor): The predicted output from the model.
        labels (Tensor): The ground truth label.
        params (dict): The parameters passed by the user yaml.

    Returns:
        loss (Tensor): The computed loss from the label and the prediction.
```

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/step.py
> +    Function that steps the GAN model for a single batch
Update comment style.

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/training_loop.py
> +    Function to train a GAN network for a single epoch.
Update comment style.

2024-03-13 16:39 UTC, sarthakpati commented on GANDLF/GAN/compute/training_loop.py
> +        optimizer_d.zero_grad()
Wondering if it would make sense to split all this code into one or more `step` functions for maintainability... Thoughts?

2024-03-13 17:19 UTC, szmazurek commented on GANDLF/GAN/compute/training_loop.py
> +        optimizer_d.zero_grad()
That is actually right - do you think to that I should go for it right now or we will split it in the future as a separate pr? Maintainability-wise, this is definetly better option.

2024-03-13 17:20 UTC, szmazurek commented on GANDLF/GAN/compute/forward_pass.py
> +    # I really do not get it
I will think about it, there can be more of such desperation artifacts when I was trying to solve it :p anyway, will come back to you with this one

2024-03-13 17:30 UTC, sarthakpati commented on GANDLF/GAN/compute/training_loop.py
> +        optimizer_d.zero_grad()
I would suggest to do it now itself so that we are not scrambling with additional stuff later...

2024-03-13 17:30 UTC, sarthakpati commented on GANDLF/GAN/compute/forward_pass.py
> +    # I really do not get it
Okay - but the comment needs to make some sense. 🤣

2024-03-14 09:48 UTC, szmazurek commented on GANDLF/GAN/compute/forward_pass.py
> +    # I really do not get it
Ok, I know what I meant, added that to the comment :P

2024-03-14 10:27 UTC, szmazurek commented on GANDLF/GAN/compute/forward_pass.py
> +    # I really do not get it
Solved

2024-03-14 10:38 UTC, szmazurek commented on GANDLF/GAN/compute/generic.py
> +    """Creates a latent vector of given size and adjusts the dimensions
Done

2024-03-14 10:38 UTC, szmazurek commented on GANDLF/GAN/compute/generic.py
> +    parameters, train_csv=None, val_csv=None, device="cpu"
Done

2024-03-14 10:41 UTC, szmazurek commented on GANDLF/GAN/compute/generic.py
> +    Function to get the fixed latent vector for inference or validation.
Done

2024-03-14 10:42 UTC, szmazurek commented on GANDLF/GAN/compute/inference_loop.py
> +    """Normalizes the input tensor to be in the range [0, 1]. Operation is
Done

2024-03-14 10:50 UTC, szmazurek commented on GANDLF/GAN/compute/inference_loop.py
> +        """Utility function to normalize the input image, the same as in
Done

2024-03-14 10:57 UTC, szmazurek commented on GANDLF/GAN/compute/loss_and_metric.py
> +    This function computes the output of a metric function.
Done

2024-03-14 11:01 UTC, szmazurek commented on GANDLF/GAN/compute/loss_and_metric.py
> +        loss (Tensor): The computed loss from the label and the prediction.
done, will be commited

2024-03-14 11:26 UTC, szmazurek commented on GANDLF/GAN/compute/training_loop.py
> +    Function to train a GAN network for a single epoch.
Done

2024-03-14 15:12 UTC, szmazurek commented on GANDLF/GAN/compute/training_loop.py
> +        optimizer_d.zero_grad()
I am running a training to see if it did not break anything, I have moved them to separate functions, as well as backward pass itself. Will push shortly if the test is ok.

2024-03-14 16:02 UTC, szmazurek commented on GANDLF/GAN/compute/training_loop.py
> +        optimizer_d.zero_grad()
Done, changes in all files are purely code formatting related. The changes are in training_loop.py file, GAN steps extracted and refactored.

2024-03-15 13:35 UTC, sarthakpati reviewed
Small question

2024-03-15 13:35 UTC, sarthakpati commented on GANDLF/GAN/compute/training_loop.py
> +        fill_value=1,
Why is the fill value changing from `0` to `1`?

2024-03-15 13:40 UTC, szmazurek commented on GANDLF/GAN/compute/training_loop.py
> +        fill_value=1,
in previous pr I set it incorrectly to 0, it should be 1

2024-03-15 13:50 UTC, sarthakpati commented on GANDLF/GAN/compute/training_loop.py
> +        fill_value=1,
Understood.

2024-03-15 13:50 UTC, sarthakpati approved these changes
LGTM

2024-03-15 18:27 UTC, merged