Modification for main modules compatibility
szmazurek/GaNDLF pull request #31
Opened 2024-03-10 11:08 UTC by szmazurek

Fixes #816

## Proposed Changes
- modification for proper scheduler and optimizer handling
- modification for proper onnx handling
- GAN logger instance
- adding model to the models registry

## Checklist

- [X] [`CONTRIBUTING`](https://github.com/mlcommons/GaNDLF/blob/master/CONTRIBUTING.md) guide has been followed.
- [X] PR is based on the [current GaNDLF master ](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop?platform=windows).
- [X] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [X] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [X] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) file.
- [ ] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate.
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/mlcommons/GaNDLF); if coverage is reduced, please give explanation.
- [ ] If customized dependency installation is required (i.e., a separate `pip install` step is needed for PR to be functional), please ensure it is reflected in all the files that control the CI, namely: [python-test.yml](https://github.com/mlcommons/GaNDLF/blob/master/.github/workflows/python-test.yml), and all docker files [[1](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-CPU),[2](https://github.com/mlcommons/GaNDLF/blob/devcontainer_build_fix/Dockerfile-CUDA11.6),[3](https://github.com/mlcommons/GaNDLF/blob/master/Dockerfile-ROCm)].

2024-03-12 13:30 UTC, sarthakpati reviewed
Most of it is fine. Just 1 question to address.

2024-03-12 13:30 UTC, sarthakpati commented on GANDLF/models/__init__.py
> +from .dcgan import DCGAN
Not sure if this is needed for **this** PR...?

2024-03-12 13:30 UTC, sarthakpati commented on GANDLF/models/__init__.py
> +    "dcgan": DCGAN,
Not sure if this is needed for **this** PR...?

2024-03-12 19:36 UTC, szmazurek commented on GANDLF/models/__init__.py
> +from .dcgan import DCGAN
nah, you are right. Will move it into the dcgan branch

2024-03-12 19:36 UTC, szmazurek commented on GANDLF/models/__init__.py
> +    "dcgan": DCGAN,
as above

2024-03-12 20:23 UTC, sarthakpati commented on GANDLF/models/__init__.py
> +from .dcgan import DCGAN
Thanks!

2024-03-12 20:34 UTC, szmazurek commented
> Most of it is fine. Just 1 question to address.

Waiting for tests to pass, them will merge

2024-03-13 15:00 UTC, sarthakpati requested changes
What's the version of `black` you are using, BTW? Is it different from what's in [`setup.py`](https://github.com/mlcommons/GaNDLF/blob/master/setup.py#L85)?

Also, minor changes.

2024-03-13 15:00 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +                ):  # check if any of the special cases are present
Run `black` through this again.
```suggestion
                # check if any of the special cases are present
                if (
                    case in _class
                ):
```

2024-03-13 15:00 UTC, sarthakpati commented on GANDLF/data/ImagesFromDataFrame.py
> +        extension,
```suggestion
        resized_image: str,
        output_dir: str,
        subject_id: str,
        channel_str: str,
        loader_type: str,
        extension: str,
```

2024-03-13 15:00 UTC, sarthakpati commented on GANDLF/logger.py
> +        """
Update comment style.

2024-03-13 15:00 UTC, sarthakpati commented on GANDLF/logger.py
> +            epoch_metrics (dict): The epoch metrics
Update comment style.

2024-03-13 15:00 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +    This is the optimizer for the discriminator.
```suggestion
        optimizer_1 (torch.optim): The optimizer for training. In case of GANs, this is the optimizer for the generator.
        optimizer_2 (torch.optim): The second optimizer, used only in case of GANs. This is the optimizer for the discriminator.
```

2024-03-13 15:00 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +            optimizer_2.load_state_dict(optimizer_2.state_dict())
Wondering if it would be better to have a list or dict of optimizers instead of just 2...?

2024-03-13 17:24 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +            optimizer_2.load_state_dict(optimizer_2.state_dict())
It is one of possible solutions, this was the first thing I come up with. Should I add that to this pr or we add it in the future?

2024-03-13 17:26 UTC, szmazurek commented
> What's the version of `black` you are using, BTW? Is it different from what's in [`setup.py`](https://github.com/mlcommons/GaNDLF/blob/master/setup.py#L85)?
> 
> Also, minor changes.

I have the same, but probably I have different line length settings - I am in the 79 length clan, I believe default is 120 line length? Should I change that back?

2024-03-13 17:31 UTC, sarthakpati commented
> > What's the version of `black` you are using, BTW? Is it different from what's in [`setup.py`](https://github.com/mlcommons/GaNDLF/blob/master/setup.py#L85)?
> > Also, minor changes.
> 
> I have the same, but probably I have different line length settings - I am in the 79 length clan, I believe default is 120 line length? Should I change that back?

How are you suggesting black to make that change? I am curious because I don't think GaNDLF is setting that in the linting configuration...

2024-03-14 09:36 UTC, szmazurek commented
> > > What's the version of `black` you are using, BTW? Is it different from what's in [`setup.py`](https://github.com/mlcommons/GaNDLF/blob/master/setup.py#L85)?
> > > Also, minor changes.
> > 
> > 
> > I have the same, but probably I have different line length settings - I am in the 79 length clan, I believe default is 120 line length? Should I change that back?
> 
> How are you suggesting black to make that change? I am curious because I don't think GaNDLF is setting that in the linting configuration...

I am setting that in the vscode black plugin settings, I have it configured that vscode automatically formats the document upon saving

2024-03-14 13:16 UTC, sarthakpati commented
> > > > What's the version of `black` you are using, BTW? Is it different from what's in [`setup.py`](https://github.com/mlcommons/GaNDLF/blob/master/setup.py#L85)?
> > > > Also, minor changes.
> > > 
> > > 
> > > I have the same, but probably I have different line length settings - I am in the 79 length clan, I believe default is 120 line length? Should I change that back?
> > 
> > 
> > How are you suggesting black to make that change? I am curious because I don't think GaNDLF is setting that in the linting configuration...
> 
> I am setting that in the vscode black plugin settings, I have it configured that vscode automatically formats the document upon saving

Okay - do you mind setting it to the default (i.e., 120)? It's just that if this is not a parameter that we are controlling on the black configuration for GaNDLF, these changes will come up for each contributor... 🤕

2024-03-14 13:17 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +            optimizer_2.load_state_dict(optimizer_2.state_dict())
Do you mind adding it now so that are _kind of_ future proofed? 😆

2024-03-14 15:01 UTC, szmazurek commented
> > > > > What's the version of `black` you are using, BTW? Is it different from what's in [`setup.py`](https://github.com/mlcommons/GaNDLF/blob/master/setup.py#L85)?
> > > > > Also, minor changes.
> > > > 
> > > > 
> > > > I have the same, but probably I have different line length settings - I am in the 79 length clan, I believe default is 120 line length? Should I change that back?
> > > 
> > > 
> > > How are you suggesting black to make that change? I am curious because I don't think GaNDLF is setting that in the linting configuration...
> > 
> > 
> > I am setting that in the vscode black plugin settings, I have it configured that vscode automatically formats the document upon saving
> 
> Okay - do you mind setting it to the default (i.e., 120)? It's just that if this is not a parameter that we are controlling on the black configuration for GaNDLF, these changes will come up for each contributor... 🤕

I do not - will do that! And actually, default turns out to be 88 chars/line, so this is what I am going to set

2024-03-14 16:47 UTC, szmazurek commented on GANDLF/logger.py
> +        """
Done

2024-03-14 16:48 UTC, szmazurek commented on GANDLF/logger.py
> +            epoch_metrics (dict): The epoch metrics
Done

2024-03-14 17:48 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +            optimizer_2.load_state_dict(optimizer_2.state_dict())
Added that, will still need to modify it in one place for GANs but that after the merge

2024-03-15 13:49 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +        tqdm(
Is the lines for `black` 120 or 79 for this file?

2024-03-15 13:49 UTC, sarthakpati reviewed
Looks good. Just confirm what the number of characters are for black for these files (it seems like it is less than what it was before).

2024-03-15 18:32 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        tqdm(
It was with the default, so 88, I mentioned that in the last comment in the previous conversation. Should I go with 120 instead? BTW - I re-blacked once again all files in this pr, pushing now

2024-03-15 18:33 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        tqdm(
Ha! Strange thing, I manually moved it back to the version with this code in single line black did not move it back to the previous format. Dunno why I had to do it manually

2024-03-17 17:50 UTC, sarthakpati requested changes
I don't think the `black` line-length setting was set properly. Perhaps this should be done using a project-level setting.

2024-03-17 17:50 UTC, sarthakpati commented on GANDLF/logger.py
> +            row = row[:-1]  # ??
What is this comment about? 😆

2024-03-17 17:50 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +        )
Seems like the line length is <88 for this block.

2024-03-17 17:57 UTC, sarthakpati commented
> I don't think the `black` line-length setting was set properly. Perhaps this should be done using a project-level setting.

[This PR](https://github.com/mlcommons/GaNDLF/pull/820) should set this up correctly.

2024-03-18 09:01 UTC, szmazurek commented on GANDLF/logger.py
> +            row = row[:-1]  # ??
I was wondering what this line does :P But I managed to understand why it is like that, I think I will remove it :P

2024-03-18 09:09 UTC, szmazurek commented on GANDLF/logger.py
> +            row = row[:-1]  # ??
removed

2024-03-18 09:11 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        )
It was like 1 character (last comma in the brackets) that was preventing that from being set to single-line version. Removed it, also I have installed black from main branch, will use this one now.

2024-03-18 13:13 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +        )
Oh okay. The change doesn't seem to have worked for all files, though. For example:

![image](https://github.com/szmazurek/GaNDLF/assets/11719673/ca7d3eb7-9bd7-4171-a39a-ecd089923f7c)

Can you confirm?

2024-03-18 14:26 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        )
Look -  when I ran the black from CMD, there was no difference from the file I have commited here. However, some lines  got changed when I passed the -C flag, which stands for "don't go to newline if there is a trailing comma" (you can see it with black --help). Regarding the line you mentioned, take a look at my editor - I have a ruler set for 88 chars, and this one is slightly over that:
![image](https://github.com/szmazurek/GaNDLF/assets/48680634/55850f77-198a-4a06-9495-ab84cf05d906)

2024-03-18 14:33 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        )
Pushed the files ran with black with the commands I mentioned, give them a look and let's see if it did the trick. If so, maybe the -C flag should go into main branch for gandlf in extension config?

2024-03-18 15:46 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +        )
> -C flag should go into main branch for gandlf in extension config

Do you know how to set this up on the config? If so, can you please put in the PR?

2024-03-18 16:34 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        )
Short answer - no idea, but will give it a shot

2024-03-18 17:03 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        )
Edit - there are cases online where people set that in toml. I did it and installed correctly, however vscode does not give a damn about that for some reason. Explicitly setting this in the vscode ext settings works, but from cmd I still need the -C flag. No idea how to get over that, I have separate branch ready if you still want it to be commited

2024-03-18 17:15 UTC, sarthakpati commented on GANDLF/utils/tensor.py
> +        )
Yes, let's put that in as a PR. Thanks!

2024-03-18 21:38 UTC, szmazurek commented on GANDLF/utils/tensor.py
> +        )
Ok done. Closing then, if nothing elese then I am merging

2024-03-19 12:53 UTC, sarthakpati approved these changes

2024-03-19 14:14 UTC, merged